#
# Makefile for the s3c framebuffer driver
#

obj-$(CONFIG_FB_S3C)		+= s3cfb.o
obj-$(CONFIG_FB_S3C)		+= s3cfb_spi.o
obj-$(CONFIG_PLAT_S3C64XX)	+= s3cfb_fimd4x.o
obj-$(CONFIG_PLAT_S5P64XX)	+= s3cfb_fimd5x.o
obj-$(CONFIG_PLAT_S5PC1XX)	+= s3cfb_fimd5x.o
obj-$(CONFIG_FB_S3C_LTE480WV)	+= s3cfb_lte480wv.o
obj-$(CONFIG_FB_S3C_LTV350QV)	+= s3cfb_ltv350qv.o
obj-$(CONFIG_FB_S3C_LTS222QV)	+= s3cfb_lts222qv.o
obj-$(CONFIG_FB_URBETTER_UT_LCD43C_D)	+= s3cfb_UT_LCD43C_D.o
obj-$(CONFIG_FB_URBETTER_UT_LCD5A)	+= s3cfb_UT_LCD5A.o
obj-$(CONFIG_FB_URBETTER_UT_LCD7A)	+= s3cfb_UT_LCD7A.o
obj-$(CONFIG_FB_URBETTER_UT_LCD104B)	+= s3cfb_UT_LCD104B.o
obj-$(CONFIG_FB_URBETTER_UT_VGA)	+= s3cfb_UT_VGA.o
obj-$(CONFIG_FB_URBETTER_UT_SVGA)	+= s3cfb_UT_SVGA.o
